
services:
  db:
    image: postgres:13
    container_name: billing-db
    environment:
      POSTGRES_DB: billings
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: moskova1945
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: billing-microservice
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: moskova1945
      DB_NAME: billings
      DB_PORT: 5432
    depends_on:
      - db
    volumes:
      - C:/Users/HP VICTUS/Documents/GitHub/Billing_Microservice/.env:/app/.env  # Agrega esta línea
volumes:
  postgres_data: